/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder */

#ifndef _Included_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
#define _Included_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    InitDecoder
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_InitDecoder
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    DeinitDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_DeinitDecoder
  (JNIEnv *, jclass);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    DecodeAndConvert
 * Signature: ([B[IJ)I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_DecodeAndConvert
  (JNIEnv *, jclass, jbyteArray, jintArray, jlong);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    InitParser
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_InitParser
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    DeinitParser
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_DeinitParser
  (JNIEnv *, jclass);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    getVideoLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_getVideoLength
  (JNIEnv *, jclass);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    getVideoWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_getVideoWidth
  (JNIEnv *, jclass);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    getVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_getVideoHeight
  (JNIEnv *, jclass);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    getVideoCoding
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_getVideoCoding
  (JNIEnv *, jclass);

/*
 * Class:     com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder
 * Method:    getVideoSample
 * Signature: ([I)Lcom/orangelabs/rcs/core/ims/protocol/rtp/codec/video/h263/decoder/VideoSample;
 */
JNIEXPORT jobject JNICALL Java_com_orangelabs_rcs_core_ims_protocol_rtp_codec_video_h263_decoder_NativeH263Decoder_getVideoSample
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
